# Generated by Django 3.1.1 on 2020-09-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
